import type { Upgrade } from './progression';
export type UIAction='start'|'resume'|'restart'|'menu'|'pause'|'mute'|'music'|'quality'|'motion'|'assist';
export interface HUDData {health:number;maxHealth:number;score:number;best:number;wave:number;waveName:string;remaining:number;progress:number;weapon:number;ammo:number;capacity:number;reload:number;dash:number;dashProgress:number;energy:number;pulseCost:number;combo:number;kills:number;time:number;bossHealth:number|null;upgrades:string[]}
export function readSave<T>(key:string,fallback:T):T {try{const data=localStorage.getItem(`last-signal:${key}`);return data?JSON.parse(data) as T:fallback;}catch{return fallback;}}
export function writeSave(key:string,value:unknown):void {try{localStorage.setItem(`last-signal:${key}`,JSON.stringify(value));}catch{/* Local storage is optional. */}}
const mark=`<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M4 27V5h6v16h18v6zm12-11V5h5v11zm11-6V5h5v5z" fill="currentColor"/></svg>`;
const soundIcon=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9h4l5-4v14l-5-4H4zM17 8c3 2 3 6 0 8m3-11c5 4 5 10 0 14" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>`;
export class UI {
  onAction:(action:UIAction)=>void=()=>{};onUpgrade:(id:string)=>void=()=>{};onVolume:(v:number)=>void=()=>{};
  root:HTMLElement;
  private els:Record<string,HTMLElement>={};
  private noticeTime=0;private bannerTime=0;
  private floaters:{el:HTMLElement;x:number;y:number;life:number}[]=[];
  private lastUpgrades='';
  constructor(host:HTMLElement){
    this.root=document.createElement('div');this.root.id='interface';host.append(this.root);
    this.root.innerHTML=`
      <div id="vignette"></div><div id="damage-wash"></div><div id="crosshair"><i></i><i></i><i></i><i></i><b></b></div>
      <header id="masthead"><a class="brand" href="#" aria-label="Last Signal home">${mark}<span>RELAY SYSTEMS<span class="brand-sub">AUTONOMOUS DEFENSE DIVISION</span></span></a><div class="header-right"><span class="online-dot"></span><span>LOCAL SYSTEM ONLINE</span><button id="sound" class="icon-button" data-action="mute" aria-label="Toggle sound" title="Toggle sound (M)">${soundIcon}</button><button id="pause-button" class="icon-button hidden" data-action="pause" aria-label="Pause game" title="Pause (Esc)">Ⅱ</button></div></header>
      <main id="menu" class="screen">
        <div class="hero"><div class="eyebrow"><span class="little-line"></span> AN ISOLATED SIGNAL. A FINAL STAND.</div><h1>LAST<br>SIGNAL<span>.</span></h1><p class="hero-copy">The city went quiet.<br>Keep the signal alive.</p><button class="primary deploy" data-action="start"><span>DEPLOY OPERATOR</span><span class="arrow">↗</span></button><div class="menu-links"><button data-panel="manual">FIELD MANUAL <span>↗</span></button><span>/</span><button data-panel="settings">SETTINGS <span>↗</span></button></div><div class="personal-best"><span>PERSONAL BEST</span><b id="menu-best">000000</b></div></div>
        <div class="arena-caption"><div class="caption-cross">+</div><div><span class="eyebrow">THE LAST ACTIVE RELAY</span><strong>OUTPOST 09</strong><span>35° 41′ N &nbsp; / &nbsp; 139° 41′ E</span></div><div class="signal-bars"><i></i><i></i><i></i><i></i><i></i></div></div>
        <footer class="menu-footer"><span><i class="live-dot"></i> A SINGLE-PLAYER SURVIVAL TRANSMISSION</span><div><span>07 ENCOUNTERS</span><span>ONE LAST SIGNAL</span></div><span class="version">V.1.0 &nbsp; // &nbsp; HEADPHONES RECOMMENDED</span></footer>
      </main>
      <div id="hud" class="hidden">
        <section class="vitals hud-panel"><div class="micro">OPERATOR <span>01</span></div><div class="health-values"><strong id="health">100</strong><span>/ <span id="max-health">100</span> <small>INTEGRITY</small></span><span id="health-icon">+</span></div><div class="health-track"><i id="health-fill"></i></div></section>
        <section class="wave-hud"><div class="micro"><span id="wave-name">FIRST CONTACT</span><span id="wave-count">01 / 07</span></div><div id="wave-segments">${Array.from({length:7},(_,i)=>`<i data-wave="${i+1}"></i>`).join('')}</div><div class="wave-meta"><span id="objective">HOLD THE RELAY</span><span id="wave-time">00:45</span></div></section>
        <section class="score-hud"><div class="micro">TRANSMISSION SCORE</div><strong id="score">000000</strong><span id="combo"></span></section>
        <div id="boss-hud" class="hidden"><div><span>WARDEN // AUTONOMOUS SIEGE UNIT</span><span id="boss-phase">PHASE 01</span></div><div class="boss-track"><i id="boss-fill"></i></div></div>
        <section class="weapon-hud hud-panel"><div class="weapon-switch"><button data-weapon="0" class="selected"><kbd>1</kbd> NEEDLE</button><button data-weapon="1"><kbd>2</kbd> BREAKER</button><span>Q TO SWITCH</span></div><div class="weapon-info"><svg id="weapon-drawing" viewBox="0 0 140 40" aria-hidden="true"><path d="M8 15h81v-5h17v7h25v5h-30v5H63l-7 9H44l3-11H27l-7 8H9l8-14H8z" fill="currentColor"/><path d="M50 12h34v-3H50z" fill="currentColor"/></svg><div><strong id="ammo">28</strong><span>/ <span id="capacity">28</span></span></div></div><div class="weapon-caption"><span id="weapon-type">AUTOMATIC RIFLE</span><span id="reload-label"><kbd>R</kbd> RELOAD</span></div><div class="reload-track"><i id="reload-fill"></i></div></section>
        <section class="abilities"><div class="ability dash"><div class="ability-icon">»</div><div><div class="micro">PHASE DASH <kbd>SHIFT</kbd></div><div id="dash-cells"><i></i><i></i></div><span>BRIEF INVULNERABILITY</span></div></div><div class="ability pulse"><div class="ability-icon">ϟ</div><div><div class="micro">DISCHARGE <kbd>SPACE</kbd></div><div class="energy-track"><i id="energy-fill"></i></div><span id="energy-text">35 / 100 ENERGY</span></div></div></section>
        <div id="build-strip"></div><div id="run-time">00:00</div><div id="tutorial"><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> MOVE <span>·</span> MOUSE AIM <span>·</span> HOLD CLICK TO FIRE</div>
      </div>
      <div id="banner" class="hidden"><div id="banner-kicker"></div><strong id="banner-title"></strong><p id="banner-sub"></p></div><div id="notice" role="status"></div><div id="floaters"></div>
      <div id="upgrade" class="overlay hidden"><div class="upgrade-content"><div class="eyebrow">TRANSMISSION SECURED <span id="upgrade-wave">01 / 07</span></div><h2>Adapt. Then survive.</h2><p class="overlay-copy">Choose one permanent augmentation. Integrity restored by 25.</p><div id="upgrade-cards"></div><div class="upgrade-footer"><span>THE ARENA IS PAUSED. TAKE YOUR TIME.</span><span>SELECT WITH MOUSE OR KEYS 1 — 3</span></div></div></div>
      <div id="pause" class="overlay hidden"><div class="pause-content"><div class="eyebrow">TRANSMISSION ON HOLD</div><h2>Take a breath.</h2><p class="overlay-copy">The relay can wait.</p><button class="primary" data-action="resume">RESUME TRANSMISSION <span>↗</span></button><button class="secondary" data-panel="settings">SETTINGS</button><button class="text-button" data-action="restart">RESTART RUN</button><button class="text-button" data-action="menu">RETURN TO TITLE</button><div class="pause-controls"><span><kbd>WASD</kbd> MOVE</span><span><kbd>SHIFT</kbd> DASH</span><span><kbd>SPACE</kbd> DISCHARGE</span><span><kbd>Q</kbd> SWITCH</span><span><kbd>R</kbd> RELOAD</span><span><kbd>ESC</kbd> RESUME</span></div></div></div>
      <div id="ended" class="overlay hidden"><div class="end-content"><div class="eyebrow" id="end-kicker">OPERATOR CONNECTION TERMINATED</div><h2 id="end-title">Signal lost.</h2><p class="overlay-copy" id="end-copy"></p><div class="end-score"><span>FINAL TRANSMISSION SCORE</span><strong id="end-score">000000</strong><b id="new-best"></b></div><div class="end-stats"><div><span>ENCOUNTER</span><strong id="end-wave"></strong></div><div><span>ELIMINATIONS</span><strong id="end-kills"></strong></div><div><span>TIME ACTIVE</span><strong id="end-time"></strong></div></div><button class="primary" data-action="restart">REDEPLOY OPERATOR <span>↗</span></button><button class="text-button" data-action="menu">RETURN TO TITLE</button></div></div>
      <div id="panel" class="overlay hidden"><div class="panel-content"><button id="close-panel" class="close-button" aria-label="Close panel">×</button><div id="manual-content"><div class="eyebrow">OPERATOR BRIEFING / 09</div><h2>Keep it alive.</h2><p class="overlay-copy">Survive six 45-second encounters, then destroy the Warden to restore the last relay. Clear the remaining enemies after each encounter to select an upgrade.</p><div class="manual-grid"><div><h3>01 / MOVE WITH PURPOSE</h3><p><kbd>WASD</kbd> move · Mouse aims · Hold left click to shoot. <kbd>SHIFT</kbd> dashes in your movement direction and grants brief invulnerability. Two charges.</p></div><div><h3>02 / PICK YOUR MOMENT</h3><p><kbd>1</kbd> Needle: precise automatic rifle. <kbd>2</kbd> Breaker: devastating close-range scattergun. <kbd>Q</kbd> switches. <kbd>R</kbd> reloads. Ammunition reserves are unlimited.</p></div><div><h3>03 / CLOSE THE CIRCUIT</h3><p>Collect lime fragments to charge <kbd>SPACE</kbd> Discharge: an energy blast that damages enemies and erases nearby projectiles. Cyan crosses repair integrity.</p></div><div><h3>04 / READ THE THREAT</h3><p>Coral crawlers pursue. Amber gunners take aim. Pink chargers lock a direction before rushing. Leave red impact zones. Shoot orange canisters to trigger chain explosions.</p></div></div><div class="manual-note">Cover blocks shots from both sides. Chain eliminations for a score multiplier. Each augmentation lasts for the entire run.</div></div><div id="settings-content" class="hidden"><div class="eyebrow">OPERATOR PREFERENCES</div><h2>Make it yours.</h2><div class="setting"><div><strong>Master volume</strong><span>Procedural sound. No outside transmissions.</span></div><input id="volume" aria-label="Master volume" type="range" min="0" max="100" value="50"></div><div class="setting"><div><strong>Ambient rhythm</strong><span>A quiet pulse under the action.</span></div><button data-action="music" id="music-toggle" class="toggle" aria-pressed="true">ON</button></div><div class="setting"><div><strong>Visual quality</strong><span>Soft shadows and bloom.</span></div><button data-action="quality" id="quality-toggle" class="toggle" aria-pressed="true">HIGH</button></div><div class="setting"><div><strong>Camera effects</strong><span>Subtle camera shake on impact.</span></div><button data-action="motion" id="motion-toggle" class="toggle" aria-pressed="true">ON</button></div><div class="setting"><div><strong>Assist mode</strong><span>35% less incoming damage. Separate personal best.</span></div><button data-action="assist" id="assist-toggle" class="toggle" aria-pressed="false">OFF</button></div><p class="settings-footnote">Preferences are saved on this device. <kbd>M</kbd> toggles all audio.</p></div></div></div>
    `;
    this.root.querySelectorAll<HTMLElement>('[id]').forEach(el=>{this.els[el.id]=el;});
    this.root.addEventListener('click',e=>{const target=e.target as HTMLElement;const action=target.closest<HTMLElement>('[data-action]');if(action)this.onAction(action.dataset.action as UIAction);const panel=target.closest<HTMLElement>('[data-panel]');if(panel)this.openPanel(panel.dataset.panel!);const upgrade=target.closest<HTMLElement>('[data-upgrade]');if(upgrade)this.onUpgrade(upgrade.dataset.upgrade!);const weapon=target.closest<HTMLElement>('[data-weapon]');if(weapon)dispatchEvent(new KeyboardEvent('keydown',{code:weapon.dataset.weapon==='0'?'Digit1':'Digit2'}));});
    this.els['close-panel'].onclick=()=>this.closePanel();
    this.els['volume'].addEventListener('input',e=>this.onVolume(Number((e.target as HTMLInputElement).value)/100));
    this.root.querySelector('.brand')!.addEventListener('click',e=>e.preventDefault());
  }
  private text(id:string,value:string):void {if(this.els[id].textContent!==value)this.els[id].textContent=value;}
  show(state:string):void {for(const name of ['menu','hud','upgrade','pause','ended'])this.els[name].classList.toggle('hidden',name!==(state==='playing'?'hud':state));this.els['pause-button'].classList.toggle('hidden',state!=='playing');this.root.classList.toggle('in-game',state==='playing');document.body.classList.toggle('playing',state==='playing');this.els['crosshair'].classList.toggle('hidden',state!=='playing');if(state!=='playing')this.els['banner'].classList.add('hidden');}
  setBest(best:number):void{this.text('menu-best',String(best).padStart(6,'0'));}
  openPanel(name:string):void{this.els['panel'].classList.remove('hidden');this.els['manual-content'].classList.toggle('hidden',name!=='manual');this.els['settings-content'].classList.toggle('hidden',name!=='settings');this.els['close-panel'].focus();}
  closePanel():void{this.els['panel'].classList.add('hidden');}
  get panelOpen():boolean{return !this.els['panel'].classList.contains('hidden');}
  settings(s:{enabled:boolean;music:boolean;quality:boolean;motion:boolean;assist:boolean;volume:number}):void{this.els['sound'].classList.toggle('muted',!s.enabled);this.els['sound'].setAttribute('aria-pressed',String(!s.enabled));for(const key of ['music','quality','motion','assist'] as const){this.text(`${key}-toggle`,key==='quality'?(s[key]?'HIGH':'LOW'):(s[key]?'ON':'OFF'));this.els[`${key}-toggle`].setAttribute('aria-pressed',String(s[key]));}(this.els['volume'] as HTMLInputElement).value=String(s.volume*100);}
  update(d:HUDData):void {
    this.text('health',String(Math.ceil(d.health)).padStart(3,'0'));this.text('max-health',String(d.maxHealth));this.els['health-fill'].style.width=`${d.health/d.maxHealth*100}%`;this.els['vignette'].classList.toggle('critical',d.health/d.maxHealth<.3);this.els['health'].classList.toggle('low',d.health/d.maxHealth<.3);
    this.text('score',String(d.score).padStart(6,'0'));this.text('wave-name',d.waveName.toUpperCase());this.text('wave-count',`${String(d.wave).padStart(2,'0')} / 07`);this.text('wave-time',d.wave===7?'FINAL ENCOUNTER':d.remaining>0?UI.time(d.remaining):'CLEAR HOSTILES');this.text('objective',d.wave===7?'DESTROY THE WARDEN':'HOLD THE RELAY');
    this.root.querySelectorAll<HTMLElement>('[data-wave]').forEach(el=>{const wave=Number(el.dataset.wave);el.classList.toggle('complete',wave<d.wave);el.classList.toggle('current',wave===d.wave);el.style.setProperty('--progress',`${d.progress*100}%`);});
    this.text('combo',d.combo>1?`×${d.combo.toFixed(1)} CHAIN`:'');this.text('ammo',String(d.ammo).padStart(2,'0'));this.text('capacity',String(d.capacity));this.text('weapon-type',d.weapon===0?'AUTOMATIC RIFLE':'SCATTERGUN / CLOSE RANGE');this.root.querySelectorAll<HTMLElement>('[data-weapon]').forEach(el=>el.classList.toggle('selected',Number(el.dataset.weapon)===d.weapon));
    this.els['reload-fill'].style.width=`${d.reload*100}%`;this.els['reload-label'].innerHTML=d.reload>0?'RELOADING…':'<kbd>R</kbd> RELOAD';
    this.els['dash-cells'].querySelectorAll<HTMLElement>('i').forEach((el,i)=>{el.classList.toggle('charged',i<d.dash);el.style.setProperty('--charge',`${i===d.dash?d.dashProgress*100:0}%`);});
    this.els['energy-fill'].style.width=`${Math.min(1,d.energy/d.pulseCost)*100}%`;this.els['energy-fill'].closest('.ability')!.classList.toggle('ready',d.energy>=d.pulseCost);this.text('energy-text',d.energy>=d.pulseCost?'DISCHARGE READY':`${Math.floor(d.energy)} / ${d.pulseCost} ENERGY`);
    this.text('run-time',UI.time(d.time));this.els['tutorial'].classList.toggle('hidden',d.time>16);
    this.els['boss-hud'].classList.toggle('hidden',d.bossHealth===null);if(d.bossHealth!==null){this.els['boss-fill'].style.width=`${d.bossHealth*100}%`;this.text('boss-phase',d.bossHealth<.45?'PHASE 02 / ENRAGED':'PHASE 01');}
    const upgrades=d.upgrades.join(' / ');if(upgrades!==this.lastUpgrades){this.lastUpgrades=upgrades;this.els['build-strip'].innerHTML=d.upgrades.map(u=>`<span>${u}</span>`).join('');}
  }
  banner(kicker:string,title:string,sub:string,duration=3.6):void{this.text('banner-kicker',kicker);this.text('banner-title',title);this.text('banner-sub',sub);this.els['banner'].classList.remove('hidden');this.bannerTime=duration;}
  notice(message:string):void{this.text('notice',message);this.noticeTime=2;this.els['notice'].classList.add('visible');}
  hurt():void {this.els['damage-wash'].classList.remove('hit');void this.els['damage-wash'].offsetWidth;this.els['damage-wash'].classList.add('hit');}
  hitMarker():void{this.els['crosshair'].classList.remove('hit');void this.els['crosshair'].offsetWidth;this.els['crosshair'].classList.add('hit');}
  floater(text:string,x:number,y:number,color=''):void{if(this.floaters.length>32)return;const el=document.createElement('span');el.textContent=text;el.className='floater';if(color)el.style.color=color;this.els['floaters'].append(el);this.floaters.push({el,x,y,life:.8});}
  tick(dt:number,mouse:{x:number;y:number}):void{this.els['crosshair'].style.transform=`translate(${mouse.x}px,${mouse.y}px)`;this.noticeTime-=dt;if(this.noticeTime<=0)this.els['notice'].classList.remove('visible');this.bannerTime-=dt;if(this.bannerTime<=0)this.els['banner'].classList.add('hidden');for(let i=this.floaters.length-1;i>=0;i--){const f=this.floaters[i];f.life-=dt;if(f.life<=0){f.el.remove();this.floaters.splice(i,1);}else{f.el.style.transform=`translate(${f.x}px,${f.y-(.8-f.life)*35}px)`;f.el.style.opacity=String(Math.min(1,f.life*3));}}}
  upgrades(choices:Upgrade[],wave:number):void {this.show('upgrade');this.text('upgrade-wave',`${String(wave).padStart(2,'0')} / 07`);this.els['upgrade-cards'].innerHTML=choices.map((u,i)=>`<button class="upgrade-card" data-upgrade="${u.id}"><div class="card-top"><span>${u.tag}</span><kbd>0${i+1}</kbd></div><div class="upgrade-icon">${u.icon}</div><h3>${u.name}</h3><p>${u.description}</p><small>${u.detail}</small><div class="card-bottom">INSTALL AUGMENTATION <span>↗</span></div></button>`).join('');}
  end(win:boolean,score:number,best:boolean,wave:number,kills:number,time:number,assist:boolean):void {this.show('ended');this.text('end-kicker',win?'TRANSMISSION RECEIVED / THE CITY IS LISTENING':'OPERATOR CONNECTION TERMINATED');this.text('end-title',win?'Signal restored.':'Signal lost.');this.text('end-copy',win?'One operator. One relay. A whole city brought back online.':'The relay is still out there. So is another chance.');this.text('end-score',String(score).padStart(6,'0'));this.text('new-best',best?`NEW PERSONAL BEST${assist?' / ASSIST':''}`:assist?'ASSIST MODE':'');this.text('end-wave',`${String(wave).padStart(2,'0')} / 07`);this.text('end-kills',String(kills));this.text('end-time',UI.time(time));}
  static time(t:number):string{const seconds=Math.max(0,Math.ceil(t));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
}
